eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
spring: 
  cloud: 
    compatibility-verifier: 
      enabled: false
